/**
 * Development seed data.
 *
 * This is realistic demo content used to make the product explorable before a
 * user has captured anything of their own. It is written through the same
 * store API as real data, so it is fully editable and deletable in the UI.
 */

import type {
  ActivityEvent,
  Answer,
  Conversation,
  Device,
  KnowledgeEdge,
  KnowledgeNode,
  Memory,
  Project,
  Settings,
  Source,
  Task,
} from "./types";

const MIN = 60_000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

export const DEFAULT_SETTINGS: Settings = {
  awareness: {
    alwaysAvailable: true,
    speechDetection: true,
    periodicScanning: true,
    scanIntervalMinutes: 10,
  },
  memory: {
    automaticMemory: true,
    decisionDetection: true,
    temporaryRetention: true,
    retentionDays: 30,
  },
  privacy: {
    localProcessingOnly: true,
    cloudServices: false,
    saveRawAudio: false,
    rawAudioStored: false,
  },
  profile: {
    name: "Prateek",
    wakeWordEnabled: false,
    simulateSpeech: true,
  },
  appearance: {
    reducedMotion: null,
    compactDensity: false,
  },
};

export interface SeedState {
  projects: Project[];
  memories: Memory[];
  sources: Source[];
  tasks: Task[];
  devices: Device[];
  conversations: Conversation[];
  activity: ActivityEvent[];
  answers: Answer[];
  knowledge: { nodes: KnowledgeNode[]; edges: KnowledgeEdge[] };
  settings: Settings;
}

export function createSeedState(now = new Date()): SeedState {
  const iso = (msAgo: number) => new Date(now.getTime() - msAgo).toISOString();

  const projects: Project[] = [
    {
      id: "p-smartline",
      name: "SmartLine",
      description:
        "Smart conveyor line — bearing health sensing, XGBoost inference and the v3 enclosure.",
      createdAt: iso(212 * DAY),
      updatedAt: iso(2 * HOUR),
      tags: ["ML", "Hardware", "Presentation"],
      status: "active",
      accent: "cyan",
    },
    {
      id: "p-neobrain",
      name: "NeoBrain",
      description: "Local-first memory system for phone and laptop. This project.",
      createdAt: iso(96 * DAY),
      updatedAt: iso(5 * HOUR),
      tags: ["Development", "Design", "Research"],
      status: "active",
      accent: "violet",
    },
    {
      id: "p-college",
      name: "College",
      description: "Coursework, assignments and exam prep for the current semester.",
      createdAt: iso(340 * DAY),
      updatedAt: iso(1 * DAY),
      tags: ["Notes", "Assignments", "Exams"],
      status: "active",
      accent: "amber",
    },
    {
      id: "p-personal",
      name: "Personal",
      description: "Device notes, preferences and everyday captures.",
      createdAt: iso(120 * DAY),
      updatedAt: iso(2 * DAY),
      tags: ["Preferences", "Device"],
      status: "active",
      accent: "green",
    },
  ];

  const memories: Memory[] = [
    {
      id: "m-1",
      title: "Use XGBoost for the final model",
      content:
        "Decision: ship XGBoost instead of the neural baseline. It reached 92.4% accuracy on the held-out fold and runs comfortably on the laptop with no cloud dependency.",
      category: "decision",
      importance: "structured",
      createdAt: iso(3 * DAY),
      updatedAt: iso(3 * DAY),
      sourceReferences: ["s-notebook"],
      projectId: "p-smartline",
      retentionType: "forever",
      status: "active",
      reason: "Detected a decision with a named alternative and a measured outcome.",
    },
    {
      id: "m-2",
      title: "Order new bearing sensors",
      content:
        "The MPU6050 units drift above 60 °C. Replace with the higher-grade sensor before the demo build.",
      category: "task",
      importance: "structured",
      createdAt: iso(4 * DAY),
      updatedAt: iso(4 * DAY),
      sourceReferences: ["s-conversation-1"],
      projectId: "p-smartline",
      retentionType: "forever",
      status: "active",
      reason: "Actionable request with a clear object and deadline.",
    },
    {
      id: "m-3",
      title: "Prefer dark mode interfaces",
      content: "Stated preference: dark, low-contrast-heavy interfaces for long working sessions.",
      category: "note",
      importance: "useful",
      createdAt: iso(4 * DAY),
      updatedAt: iso(4 * DAY),
      sourceReferences: [],
      projectId: "p-personal",
      retentionType: "forever",
      status: "active",
      reason: "Repeated preference across two sessions.",
    },
    {
      id: "m-4",
      title: "Finish the presentation by Friday",
      content: "SmartLine final deck, six slides, must include the sensor placement diagram.",
      category: "task",
      importance: "structured",
      createdAt: iso(3 * DAY),
      updatedAt: iso(1 * DAY),
      sourceReferences: ["s-presentation"],
      projectId: "p-smartline",
      retentionType: "forever",
      status: "active",
      reason: "Task with an explicit deadline.",
    },
    {
      id: "m-5",
      title: "CAD enclosure moved to v3",
      content:
        "Housing v3 lowers the lid profile by 4 mm and moves the antenna cut-out. Bearing mount radius unchanged.",
      category: "knowledge",
      importance: "important",
      createdAt: iso(2 * DAY),
      updatedAt: iso(2 * DAY),
      sourceReferences: ["s-cad"],
      projectId: "p-smartline",
      retentionType: "forever",
      status: "active",
      reason: "Revision change on an actively used design file.",
    },
    {
      id: "m-6",
      title: "Sensor placement discussion",
      content:
        "Team agreed to mount the accelerometer on the drive-side pillow block to reduce frame noise. Revisit after the new sensors arrive.",
      category: "conversation",
      importance: "important",
      createdAt: iso(2 * DAY),
      updatedAt: iso(2 * DAY),
      sourceReferences: ["s-conversation-1"],
      projectId: "p-smartline",
      retentionType: "forever",
      status: "active",
    },
    {
      id: "m-7",
      title: "Explored edge deployment",
      content:
        "Checked running inference on the ESP32. Memory budget is too tight for the full model; keeping the laptop as the Deep Brain node.",
      category: "knowledge",
      importance: "useful",
      createdAt: iso(6 * DAY),
      updatedAt: iso(6 * DAY),
      sourceReferences: ["s-code"],
      projectId: "p-smartline",
      retentionType: "30-days",
      status: "active",
    },
    {
      id: "m-8",
      title: "iQOO 15 battery behaviour on notes",
      content: "Heavy note capture runs about 6.5% per hour with local transcription only.",
      category: "note",
      importance: "useful",
      createdAt: iso(5 * DAY),
      updatedAt: iso(5 * DAY),
      sourceReferences: [],
      projectId: "p-personal",
      retentionType: "30-days",
      status: "active",
    },
    {
      id: "m-9",
      title: "Temporary: meeting moved to 4 PM",
      content: "SmartLine sync pushed to 16:00. Room unchanged.",
      category: "event",
      importance: "temp",
      createdAt: iso(26 * HOUR),
      updatedAt: iso(26 * HOUR),
      sourceReferences: [],
      projectId: "p-smartline",
      retentionType: "session",
      status: "active",
    },
    {
      id: "m-10",
      title: "Retrieval anchor: SmartLine summary",
      content:
        "Yesterday on SmartLine: trained the XGBoost model, updated the CAD enclosure to v3, discussed sensor placement, and edited the presentation.",
      category: "knowledge",
      importance: "important",
      createdAt: iso(20 * HOUR),
      updatedAt: iso(20 * HOUR),
      sourceReferences: ["s-notebook", "s-cad", "s-conversation-1", "s-presentation"],
      projectId: "p-smartline",
      retentionType: "forever",
      status: "active",
    },
    {
      id: "m-11",
      title: "Candidate: consider a bearing dataset from the lab",
      content:
        "A lab member offered a longer run-to-failure dataset (CWRU mirror). Could improve generalisation for the demo.",
      category: "knowledge",
      importance: "useful",
      createdAt: iso(40 * MIN),
      updatedAt: iso(40 * MIN),
      sourceReferences: ["s-conversation-2"],
      projectId: "p-smartline",
      retentionType: "30-days",
      status: "candidate",
      reason: "Mentioned once, likely useful for the SmartLine model.",
    },
    {
      id: "m-12",
      title: "NeoBrain: local-only retrieval first",
      content:
        "Decision for NeoBrain: keyword + vector hybrid retrieval runs on device. Cloud providers stay opt-in and off by default.",
      category: "decision",
      importance: "structured",
      createdAt: iso(30 * HOUR),
      updatedAt: iso(30 * HOUR),
      sourceReferences: [],
      projectId: "p-neobrain",
      retentionType: "forever",
      status: "active",
      reason: "Explicit product decision.",
    },
    {
      id: "m-13",
      title: "Operating systems assignment — scheduler",
      content: "Implement round-robin and priority scheduling, compare turnaround times, submit as a report.",
      category: "task",
      importance: "structured",
      createdAt: iso(2 * DAY),
      updatedAt: iso(2 * DAY),
      sourceReferences: ["s-assignment"],
      projectId: "p-college",
      retentionType: "30-days",
      status: "active",
    },
  ];

  const sources: Source[] = [
    {
      id: "s-notebook",
      type: "code",
      name: "SmartLine_Final.ipynb",
      pathOrReference: "~/SmartLine/notebooks/SmartLine_Final.ipynb",
      createdAt: iso(30 * DAY),
      modifiedAt: iso(1 * DAY + 4 * HOUR),
      indexedAt: iso(1 * DAY + 3 * HOUR),
      projectId: "p-smartline",
      metadata: { cells: 84, kernel: "python3", accuracy: "92.4%" },
      permissionStatus: "granted",
      indexStatus: "indexed",
      sizeKb: 842,
    },
    {
      id: "s-cad",
      type: "doc",
      name: "CAD_v3.step",
      pathOrReference: "~/SmartLine/cad/CAD_v3.step",
      createdAt: iso(14 * DAY),
      modifiedAt: iso(1 * DAY + 6 * HOUR),
      indexedAt: iso(1 * DAY + 5 * HOUR),
      projectId: "p-smartline",
      metadata: { revision: "v3", units: "mm" },
      permissionStatus: "granted",
      indexStatus: "indexed",
      sizeKb: 5210,
    },
    {
      id: "s-conversation-1",
      type: "audio",
      name: "Meeting_Notes.txt",
      pathOrReference: "memory://conversation/sensor-placement",
      createdAt: iso(2 * DAY),
      modifiedAt: iso(2 * DAY),
      indexedAt: iso(2 * DAY),
      projectId: "p-smartline",
      metadata: { minutes: 18, speakers: 3, rawAudio: "not stored" },
      permissionStatus: "granted",
      indexStatus: "indexed",
    },
    {
      id: "s-conversation-2",
      type: "audio",
      name: "LabFloor.mp3",
      pathOrReference: "memory://conversation/lab-floor",
      createdAt: iso(40 * MIN),
      modifiedAt: iso(40 * MIN),
      indexedAt: iso(38 * MIN),
      projectId: "p-smartline",
      metadata: { minutes: 4, rawAudio: "not stored" },
      permissionStatus: "granted",
      indexStatus: "indexed",
    },
    {
      id: "s-presentation",
      type: "pdf",
      name: "SmartLine_Architecture.pdf",
      pathOrReference: "~/SmartLine/deck/SmartLine_Architecture.pdf",
      createdAt: iso(9 * DAY),
      modifiedAt: iso(1 * DAY + 2 * HOUR),
      indexedAt: iso(1 * DAY + 2 * HOUR),
      projectId: "p-smartline",
      metadata: { pages: 24 },
      permissionStatus: "granted",
      indexStatus: "indexed",
      sizeKb: 3480,
    },
    {
      id: "s-code",
      type: "code",
      name: "esp32_firmware.cpp",
      pathOrReference: "~/SmartLine/firmware/esp32_firmware.cpp",
      createdAt: iso(40 * DAY),
      modifiedAt: iso(4 * HOUR),
      indexedAt: iso(3 * HOUR),
      projectId: "p-smartline",
      metadata: { lines: 612, target: "esp32-s3" },
      permissionStatus: "granted",
      indexStatus: "indexed",
      sizeKb: 46,
    },
    {
      id: "s-diagram",
      type: "image",
      name: "Bearing_Diagram.png",
      pathOrReference: "~/SmartLine/docs/Bearing_Diagram.png",
      createdAt: iso(11 * DAY),
      modifiedAt: iso(8 * HOUR),
      indexedAt: iso(6 * HOUR),
      projectId: "p-smartline",
      metadata: { width: 2048, height: 1400, ocr: "bearing housing, drive side" },
      permissionStatus: "granted",
      indexStatus: "indexed",
      sizeKb: 1290,
    },
    {
      id: "s-assignment",
      type: "pdf",
      name: "OS_Assignment_03.pdf",
      pathOrReference: "~/College/OS/OS_Assignment_03.pdf",
      createdAt: iso(6 * DAY),
      modifiedAt: iso(2 * DAY),
      indexedAt: iso(2 * DAY),
      projectId: "p-college",
      metadata: { pages: 6 },
      permissionStatus: "granted",
      indexStatus: "indexed",
      sizeKb: 720,
    },
    {
      id: "s-phone-photos",
      type: "dir",
      name: "Camera Roll",
      pathOrReference: "/storage/emulated/0/DCIM/Camera",
      createdAt: iso(400 * DAY),
      modifiedAt: iso(1 * HOUR),
      projectId: "p-personal",
      metadata: { items: 1284 },
      permissionStatus: "not-requested",
      indexStatus: "queued",
    },
    {
      id: "s-downloads",
      type: "dir",
      name: "Downloads",
      pathOrReference: "~/Downloads",
      createdAt: iso(200 * DAY),
      modifiedAt: iso(3 * HOUR),
      metadata: { items: 342 },
      permissionStatus: "required",
      indexStatus: "inaccessible",
      indexError: "Folder permission not granted for this workspace.",
    },
  ];

  const tasks: Task[] = [
    {
      id: "t-1",
      title: "Order new bearing sensors",
      description: "Replace the drifting MPU6050 units before the demo build.",
      status: "open",
      priority: "high",
      dueDate: iso(-2 * DAY),
      projectId: "p-smartline",
      sourceMemoryId: "m-2",
      createdAt: iso(4 * DAY),
      updatedAt: iso(4 * DAY),
    },
    {
      id: "t-2",
      title: "Finish presentation by Friday",
      description: "Six slides including the sensor placement diagram.",
      status: "in-progress",
      priority: "medium",
      dueDate: iso(-4 * DAY),
      projectId: "p-smartline",
      sourceMemoryId: "m-4",
      createdAt: iso(3 * DAY),
      updatedAt: iso(1 * DAY),
    },
    {
      id: "t-3",
      title: "Re-run the training fold with the new sensor data",
      description: "Compare against the 92.4% baseline.",
      status: "open",
      priority: "medium",
      projectId: "p-smartline",
      sourceMemoryId: "m-1",
      createdAt: iso(2 * DAY),
      updatedAt: iso(2 * DAY),
    },
    {
      id: "t-4",
      title: "Submit OS assignment 03",
      description: "Scheduler comparison report.",
      status: "open",
      priority: "high",
      dueDate: iso(-1 * DAY),
      projectId: "p-college",
      sourceMemoryId: "m-13",
      createdAt: iso(2 * DAY),
      updatedAt: iso(2 * DAY),
    },
    {
      id: "t-5",
      title: "Review NeoBrain retrieval traces",
      description: "Make sure every answer shows which memories were used.",
      status: "done",
      priority: "low",
      projectId: "p-neobrain",
      createdAt: iso(3 * DAY),
      updatedAt: iso(30 * HOUR),
    },
  ];

  const devices: Device[] = [
    {
      id: "d-iqoo",
      name: "iQOO 15",
      type: "phone",
      connectionStatus: "connected",
      lastSeen: iso(2 * MIN),
      capabilities: ["microphone", "camera", "screen capture", "local ASR", "notifications"],
      processingRole: "pocket",
      model: "Snapdragon 8 Elite · 12 GB",
      paired: true,
    },
    {
      id: "d-laptop",
      name: "Laptop",
      type: "laptop",
      connectionStatus: "syncing",
      lastSeen: iso(30_000),
      capabilities: ["file indexing", "local LLM", "embeddings", "vector store", "long-term store"],
      processingRole: "deep",
      model: "Deep Brain · 32 GB",
      syncProgress: 0.68,
      paired: true,
    },
    {
      id: "d-tablet",
      name: "Tablet",
      type: "tablet",
      connectionStatus: "disconnected",
      lastSeen: iso(9 * DAY),
      capabilities: ["reading", "annotation"],
      processingRole: "pocket",
      model: "Paired previously",
      paired: false,
    },
  ];

  const conversations: Conversation[] = [
    {
      id: "c-1",
      title: "What did I do yesterday on SmartLine?",
      createdAt: iso(20 * HOUR),
      updatedAt: iso(20 * HOUR),
      sourceReferences: ["s-notebook", "s-cad", "s-conversation-1", "s-presentation"],
      projectId: "p-smartline",
      retentionStatus: "saved",
      messages: [
        {
          id: "cm-1",
          role: "user",
          text: "What did I do yesterday on SmartLine?",
          createdAt: iso(20 * HOUR),
        },
        {
          id: "cm-2",
          role: "brain",
          text:
            "You worked on SmartLine yesterday. Here's a summary:\n1. Trained the XGBoost model (92.4% accuracy).\n2. Updated the CAD enclosure design to v3.\n3. Discussed sensor placement with the team.\n4. Edited the presentation slides.",
          createdAt: iso(20 * HOUR),
          sourceIds: ["s-notebook", "s-cad", "s-conversation-1", "s-presentation"],
        },
      ],
    },
  ];

  const activity: ActivityEvent[] = [
    {
      id: "a-1",
      type: "speech",
      title: "Speech detected",
      detail: "\"Let's use XGBoost…\"",
      at: iso(10 * MIN),
      status: "done",
      projectId: "p-smartline",
    },
    {
      id: "a-2",
      type: "context",
      title: "Context identified",
      detail: "Related to SmartLine",
      at: iso(10 * MIN),
      status: "done",
      projectId: "p-smartline",
    },
    {
      id: "a-3",
      type: "candidate",
      title: "Memory candidate",
      detail: "Potential decision detected",
      at: iso(9 * MIN),
      status: "active",
      projectId: "p-smartline",
    },
    {
      id: "a-4",
      type: "file",
      title: "File indexed",
      detail: "SmartLine_Model.ipynb",
      at: iso(9 * MIN + 40_000),
      status: "done",
    },
    {
      id: "a-5",
      type: "insight",
      title: "Insight ready",
      detail: "Potential improvement found",
      at: iso(8 * MIN),
      status: "done",
    },
    {
      id: "a-6",
      type: "listening",
      title: "Listening",
      detail: "Speech detection active",
      at: iso(30_000),
      status: "active",
    },
    {
      id: "a-7",
      type: "file",
      title: "PDF indexed",
      detail: "SmartLine_Architecture.pdf",
      at: iso(2 * HOUR),
      status: "done",
      projectId: "p-smartline",
    },
    {
      id: "a-8",
      type: "task",
      title: "Task detected",
      detail: "Order new bearing sensors",
      at: iso(9 * HOUR),
      status: "done",
      projectId: "p-smartline",
    },
    {
      id: "a-9",
      type: "decision",
      title: "Decision remembered",
      detail: "Prefer dark mode interfaces",
      at: iso(28 * HOUR),
      status: "done",
      projectId: "p-personal",
    },
    {
      id: "a-10",
      type: "insight",
      title: "Connection discovered",
      detail: "Sensor drift linked to enclosure thermal design",
      at: iso(2 * DAY),
      status: "done",
      projectId: "p-smartline",
    },
  ];

  const answers: Answer[] = [
    {
      id: "ans-1",
      question: "What did I do yesterday related to SmartLine?",
      summary: "You worked on SmartLine yesterday. Here's a summary:",
      points: [
        "Trained the XGBoost model — final training script reached 92.4% accuracy.",
        "Updated the CAD design — housing revision moved to v3.",
        "Discussed sensor placement — team agreed on the drive-side pillow block.",
        "Edited the presentation — six slides in SmartLine_Final.pptx.",
      ],
      sources: ["s-notebook", "s-cad", "s-conversation-1", "s-presentation"],
      relatedMemoryIds: ["m-1", "m-5", "m-6", "m-4"],
      projectId: "p-smartline",
      createdAt: iso(20 * HOUR),
      computedBy: "Local retrieval · on-device",
    },
    {
      id: "ans-2",
      question: "What changed in the SmartLine enclosure last week?",
      summary: "Three changes landed on the enclosure:",
      points: [
        "Housing revision moved from v2 to v3.",
        "Lid profile lowered by 4 mm to clear the cable loom.",
        "Antenna cut-out relocated; bearing mount radius unchanged.",
      ],
      sources: ["s-cad", "s-diagram"],
      relatedMemoryIds: ["m-5"],
      projectId: "p-smartline",
      createdAt: iso(6 * HOUR),
      computedBy: "Local retrieval · on-device",
    },
  ];

  const knowledgeNodes: KnowledgeNode[] = [
    { id: "k-smartline", label: "SmartLine", kind: "project", projectId: "p-smartline", weight: 1, connections: 9 },
    { id: "k-xgboost", label: "XGBoost", kind: "tool", projectId: "p-smartline", weight: 0.78, connections: 3 },
    { id: "k-sensors", label: "Sensors", kind: "hardware", projectId: "p-smartline", weight: 0.72, connections: 4 },
    { id: "k-cad", label: "CAD", kind: "artifact", projectId: "p-smartline", weight: 0.66, connections: 3 },
    { id: "k-esp32", label: "ESP32", kind: "hardware", projectId: "p-smartline", weight: 0.6, connections: 3 },
    { id: "k-bearing", label: "Bearing", kind: "concept", projectId: "p-smartline", weight: 0.62, connections: 3 },
    { id: "k-firmware", label: "Firmware", kind: "artifact", projectId: "p-smartline", weight: 0.56, connections: 2 },
    { id: "k-dataset", label: "Dataset", kind: "document", projectId: "p-smartline", weight: 0.58, connections: 2 },
    { id: "k-presentation", label: "Presentation", kind: "document", projectId: "p-smartline", weight: 0.5, connections: 2 },
    { id: "k-research", label: "Research", kind: "concept", weight: 0.48, connections: 2 },
    { id: "k-mpu", label: "MPU6050", kind: "hardware", projectId: "p-smartline", weight: 0.44, connections: 2 },
    { id: "k-meeting", label: "Meeting Notes", kind: "document", projectId: "p-smartline", weight: 0.46, connections: 2 },
    { id: "k-neobrain", label: "NeoBrain", kind: "project", projectId: "p-neobrain", weight: 0.7, connections: 3 },
    { id: "k-retrieval", label: "Retrieval", kind: "concept", projectId: "p-neobrain", weight: 0.52, connections: 2 },
    { id: "k-college", label: "College", kind: "project", projectId: "p-college", weight: 0.5, connections: 2 },
  ];

  const link = (from: string, to: string, label: string, strength: number): KnowledgeEdge => ({
    id: `e-${from}-${to}`,
    from,
    to,
    label,
    strength,
  });

  const knowledgeEdges: KnowledgeEdge[] = [
    link("k-smartline", "k-xgboost", "model", 0.95),
    link("k-smartline", "k-sensors", "hardware", 0.9),
    link("k-smartline", "k-cad", "design", 0.85),
    link("k-smartline", "k-bearing", "focus", 0.8),
    link("k-smartline", "k-presentation", "output", 0.7),
    link("k-smartline", "k-research", "context", 0.65),
    link("k-smartline", "k-firmware", "code", 0.72),
    link("k-sensors", "k-esp32", "reads through", 0.75),
    link("k-sensors", "k-mpu", "uses", 0.7),
    link("k-bearing", "k-dataset", "measured by", 0.68),
    link("k-xgboost", "k-dataset", "trained on", 0.8),
    link("k-firmware", "k-esp32", "runs on", 0.85),
    link("k-meeting", "k-smartline", "notes", 0.6),
    link("k-research", "k-neobrain", "informs", 0.4),
    link("k-neobrain", "k-retrieval", "uses", 0.75),
    link("k-neobrain", "k-smartline", "created during", 0.35),
    link("k-college", "k-research", "study", 0.3),
  ];

  return {
    projects,
    memories,
    sources,
    tasks,
    devices,
    conversations,
    activity,
    answers,
    knowledge: { nodes: knowledgeNodes, edges: knowledgeEdges },
    settings: DEFAULT_SETTINGS,
  };
}
